# Generated by Django 4.1.3 on 2022-12-06 01:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_usuario_remove_agenda_pub_date_agenda_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 1, 28, 14, 808529, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 1, 28, 14, 778522, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='medico',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 1, 28, 14, 807529, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='medico',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='medico',
            name='usuario',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.usuario'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 1, 28, 14, 808529, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 1, 28, 14, 806529, tzinfo=datetime.timezone.utc)),
        ),
    ]
