# Generated by Django 4.1.3 on 2022-12-06 02:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_alter_agenda_creation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='paciente',
        ),
        migrations.AddField(
            model_name='agenda',
            name='hora_desde',
            field=models.TimeField(default=datetime.datetime(2022, 12, 6, 2, 45, 19, 647710, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='agenda',
            name='hora_hasta',
            field=models.TimeField(default=datetime.datetime(2022, 12, 6, 2, 45, 19, 647710, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 2, 45, 19, 648710, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 2, 45, 19, 619704, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='medico',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 2, 45, 19, 646711, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.especialidad'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.usuario'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 2, 45, 19, 647710, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='usuario',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 2, 45, 19, 646711, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2022, 12, 6, 2, 45, 19, 648710, tzinfo=datetime.timezone.utc))),
                ('agenda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.agenda')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.paciente')),
            ],
        ),
    ]
